import time

T0 = time.perf_counter()  # etapa: RTT starts at the first line of the code

# Simple_tcpClient.py  --  Alice (client)
#
# Based on the class file. What was added:
#   - an RSA key pair of 4096 bits, generated by our own C core (etapas 2, 3)
#   - the public keys crossing the socket in the clear (etapa 4)
#   - the message encrypted under Bob's public key and the uppercase answer
#     decrypted with Alice's private key
#   - the same service in the other direction: Bob sends his own sentence
#     and Alice returns it in upper case
#   - RTT from the first line to the moment the uppercase text is printed
#
# Key generation starts before the socket is opened and is only waited for
# when Bob actually needs Alice's public key, so the handshake and the search
# for the primes run at the same time.
#
# Nothing is printed between T0 and T1 but the answer itself. The keys and the
# ciphertext come out afterwards: four thousand digits on a terminal cost more
# than the whole exchange.

import os
import sys
from socket import *

import rsa
import wire

# Address of Bob. Override without editing the file:
#   HOST=192.168.122.83 python3 python/Simple_tcpClient.py
serverName = os.environ.get("HOST", "192.168.122.83")
serverPort = 1300

sentence = sys.argv[1] if len(sys.argv) > 1 else rsa.STANDARD_MESSAGE
threads = int(os.environ.get("THREADS", "0"))  # 0 = one per core

print("TCP Client (Alice)\n")

# The search runs in the background from here on.
keygen = rsa.keygen_start(rsa.MODULUS_BITS, rsa.PUBLIC_EXPONENT, threads)

clientSocket = socket(AF_INET, SOCK_STREAM)
clientSocket.setsockopt(IPPROTO_TCP, TCP_NODELAY, 1)  # no 40 ms Nagle stall
clientSocket.connect((serverName, serverPort))
t_connect = time.perf_counter()

# Etapa 4: Bob's public key arrives in plain text.
_, blob = wire.recv_frame(clientSocket, wire.PUBKEY)
bob_e, bob_n = rsa.parse_public(blob)

# The message goes out before our own key is ready: Bob can already decrypt it.
payload = rsa.encrypt(blob, sentence.encode("utf-8"))
wire.send_frame(clientSocket, wire.MESSAGE, payload)
t_sent = time.perf_counter()

# Now Alice's own key is needed, so that Bob can encrypt the answer.
key = rsa.keygen_join(keygen)
t_key = time.perf_counter()
wire.send_frame(clientSocket, wire.PUBKEY, key.public)

_, answer = wire.recv_frame(clientSocket, wire.REPLY)
t_reply = time.perf_counter()

text = key.decrypt(answer).decode("utf-8")
print("Received from Make Upper Case Server: ", text)
T1 = time.perf_counter()  # RTT ends when the uppercase text is on screen

stats = key.stats
print(f"\nRTT: {(T1 - T0) * 1000:.1f} ms")
print(
    f"  key generation   {(t_key - T0) * 1000:8.1f} ms"
    f"   ({stats['threads']} threads, {stats['candidates']} Miller-Rabin tests,"
    f" {stats['sieved']} candidates removed by the sieve)"
)
print(
    f"  import + connect {(t_connect - T0) * 1000:8.1f} ms   (overlapped with the search)"
)
print(
    f"  encrypt and send {(t_sent - t_connect) * 1000:8.1f} ms   (overlapped with the search)"
)
print(f"  answer round     {(t_reply - t_key) * 1000:8.1f} ms")
print(f"  decrypt (CRT)    {(T1 - t_reply) * 1000:8.1f} ms")

# Bob's turn: Alice runs the same service for him.
_, incoming = wire.recv_frame(clientSocket, wire.MESSAGE)
received = key.decrypt(incoming).decode("utf-8")
wire.send_frame(
    clientSocket, wire.REPLY, rsa.encrypt(blob, received.upper().encode("utf-8"))
)
print("Received From Server: ", received)
print("Sent back to Server: ", received.upper())
clientSocket.close()

# Everything below is evidence. It comes last because Bob times his own
# round trip, and printing four thousand digits would land inside it.
print(f"\nBob's public key: e = {bob_e}, n = {len(bob_n) * 8} bits")
print(f"  n = {int.from_bytes(bob_n, 'big')}")

print(f"\nAlice's public key: e = {key.e}, n = {key.size * 8} bits")
print(f"  p = {key.component('p')}")
print(f"  q = {key.component('q')}")
print(f"  n = {key.component('n')}")
print(f"  d = {key.component('d')}")

print(f"\nSent to Server (encrypted, {len(payload)} bytes):")
print(f"  {payload[:16].hex(' ')} ... {payload[-16:].hex(' ')}")
print(f"Received from Server (encrypted, {len(answer)} bytes):")
print(f"  {answer[:16].hex(' ')} ... {answer[-16:].hex(' ')}")
print(f"Received from Server (encrypted, {len(incoming)} bytes):")
print(f"  {incoming[:16].hex(' ')} ... {incoming[-16:].hex(' ')}")
