# Simple_tcpServer.py  --  Bob (server)
#
# Based on the class file. What was added:
#   - an RSA key pair of 4096 bits, generated by our own C core (etapas 2, 3)
#   - the public keys crossing the socket in the clear (etapa 4)
#   - the message decrypted with Bob's private key, put in upper case as the
#     original server does, and encrypted again under Alice's public key
#   - a sentence of Bob's own, sent to Alice for the same service, so the
#     two ends talk in both directions
#
# Key generation starts before bind, so it overlaps with the wait for the
# client and never lands on Alice's RTT.

import os
import sys
import time
from socket import *

import rsa
import wire

SERVER_PORT = 1300

sentence = sys.argv[1] if len(sys.argv) > 1 else rsa.STANDARD_MESSAGE
threads = int(os.environ.get("THREADS", "0"))  # 0 = one per core

print("TCP Server (Bob)\n")

t0 = time.perf_counter()
keygen = rsa.keygen_start(rsa.MODULUS_BITS, rsa.PUBLIC_EXPONENT, threads)

serverSocket = socket(AF_INET, SOCK_STREAM)
serverSocket.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
serverSocket.bind(("", SERVER_PORT))
serverSocket.listen(5)

key = rsa.keygen_join(keygen)
stats = key.stats
print(
    f"key pair ready in {(time.perf_counter() - t0) * 1000:.1f} ms"
    f" ({stats['threads']} threads, {stats['candidates']} Miller-Rabin tests)"
)
print(f"  p = {key.component('p')}")
print(f"  q = {key.component('q')}")
print(f"  n = {key.component('n')}")
print(f"  e = {key.e}")
print(f"  d = {key.component('d')}")
print(f"\nlistening on port {SERVER_PORT}")

connectionSocket, addr = serverSocket.accept()
connectionSocket.setsockopt(IPPROTO_TCP, TCP_NODELAY, 1)
print("Connection from:", addr)

# Etapa 4: Bob's public key goes out in plain text, first thing.
wire.send_frame(connectionSocket, wire.PUBKEY, key.public)

_, ciphertext = wire.recv_frame(connectionSocket, wire.MESSAGE)
print(f"\nReceived from Client (encrypted, {len(ciphertext)} bytes):")
print(f"  {ciphertext[:16].hex(' ')} ... {ciphertext[-16:].hex(' ')}")

received = key.decrypt(ciphertext).decode("utf-8")
print("Received From Client: ", received)

capitalizedSentence = received.upper()  # processamento

# The answer waits only for Alice's public key.
_, blob = wire.recv_frame(connectionSocket, wire.PUBKEY)
alice_e, alice_n = rsa.parse_public(blob)
print(f"\nAlice's public key: e = {alice_e}, n = {len(alice_n) * 8} bits")

answer = rsa.encrypt(blob, capitalizedSentence.encode("utf-8"))
wire.send_frame(connectionSocket, wire.REPLY, answer)

print(f"Sent back to Client (encrypted, {len(answer)} bytes):")
print(f"  {answer[:16].hex(' ')} ... {answer[-16:].hex(' ')}")
print("Sent back to Client: ", capitalizedSentence)

# Bob's turn to speak. Both keys are already in hand, so this round trip is
# the cipher and the network alone, without the search for the primes.
t_send = time.perf_counter()
outgoing = rsa.encrypt(blob, sentence.encode("utf-8"))
wire.send_frame(connectionSocket, wire.MESSAGE, outgoing)
print(f"\nSent to Client (encrypted, {len(outgoing)} bytes):")
print(f"  {outgoing[:16].hex(' ')} ... {outgoing[-16:].hex(' ')}")
print("Sent to Client: ", sentence)

_, back = wire.recv_frame(connectionSocket, wire.REPLY)
print(f"\nReceived from Client (encrypted, {len(back)} bytes):")
print(f"  {back[:16].hex(' ')} ... {back[-16:].hex(' ')}")
print("Received from Make Upper Case Client: ", key.decrypt(back).decode("utf-8"))
print(
    f"\nround trip without key generation: {(time.perf_counter() - t_send) * 1000:.1f} ms"
)

connectionSocket.close()
